In [9]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array Created:\n",a)
b=np.array((3,4))
print("Array with all zeroes:\n",b)
c=np.full((3,3),6)
print("Array with all 6s:\n",c)
d=np.random.random((2,2))
print("Random array:\n",d)
import numpy as np
e=np.arange(0,30,5)
print("New array:\n",e) 
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)

Array Created:
 [[1 2 4]
 [5 8 7]]
Array with all zeroes:
 [3 4]
Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random array:
 [[0.77381554 0.59625028]
 [0.11577666 0.21301832]]
New array:
 [ 0  5 10 15 20 25]

 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]
